### ISSUE TITLE
Popup table visible on chrome

### ISSUE THREAD

**Issue by Flatlinezor** [slaFFik/CD-BP-Avatar-Bubble#19]
Hello!

For me, it's a pretty huge issue, the outer table is present with very thin lines, and even inside the actual bubble popup there are table lines present. Any way to fix this? :(

Screenshot: https://dl.dropboxusercontent.com/u/78706473/bubblebug.jpg

**Comment by slaFFik** [comment]
That's a very theme specific issue. The plugin just can't be tested with all the theme out there. You will need to add some special rules to the style.css of your theme to make the plugin work as required.
